EnglishNames = {
    "良": "Liang",
    "舌头": "Tongue",
    "尹三": "Yin San",
    "红儿": "Hong'er",
    "第一只小羊": "The first lamb",
    "翠儿": "Cui'er",
    "第二只小羊": "The second lamb",
    "琼华": "Qiong Hua",
    "第三只小羊": "The thrid lamb",
    "第五只小羊？": "The fifth lamb?",
    "小哑巴": "Little Mute",
    "第四只小羊": "The fourth lamb",
    "满穗": "Man Sui",
    "穗": "Sui",
    "爹爹": "Dad",
    "娘": "Mom",
    "奶奶": "Grandma",
    "弟弟": "Brother",
    "小猫": "Kitten",
    "胖子": "Fat Guy",
    "瘦子": "Skinny Guy",
    "观众": "Audience",
    "官兵": "Official Soldier",
    "官兵甲": "Soldier A",
    "官兵乙": "Soldier B",
    "老人": "Old Man",
    "税官": "Tax Official",
    "饿鬼": "Ghoul",
    "饿鬼甲": "Ghoul A",
    "饿鬼乙": "Ghoul B",
    "老厨子": "Old Chef",
    "杂役": "Servant",
    "女子": "Woman",
    "芸姐": "Sis Yun",
    "当铺掌柜": "Pawnshop Owner",
    "黑胖子": "Dark Fat Guy",
    "王府太监": "Royal Eunuch",
    "豚妖": "Swine Demon",
    "王府侍卫": "Royal Guard",
    "闯王": "Li",
    "“大哥”": "Boss Li",
    "反军士兵": "Rebel",
    "反军甲": "Rebel A",
    "反军乙": "Rebel B",
    "反军丙": "Rebel C",
    "闯军甲": "Soldier A",
    "船夫": "Boatman",
    "店小二": "Waiter",
    "阌乡小二": "Wenxiang Waiter",
    "乞丐": "Beggar",
    "斗鸡眼乞丐": "Squinting Beggar",
    "眨眼乞丐": "Blinking Beggar",
    "乞丐女孩": "Beggar Girl",
    "吏卒": "Guard",
    "吏卒甲": "Guard A",
    "吏卒乙": "Guard B",
    "吏卒丙": "Guard C",
    "城门守卫": "Guard",
    "守卫": "Guard",
    "早市小贩": "Morning Market Vendor",
    "鸢": "Yuan",
    "车夫": "Wagon Driver",
    "村民甲": "Villager A",
    "村民乙": "Villager B",
    "饥民": "Hungry Person",
    "盗匪头目": "Bandit Leader",
    "死者": "The Dead",
    "李老伯": "Village Elder Li",
    "壮汉": "Burly Man",
    "馒头铺老板": "Bun Stand Owner"
}